#!/bin/sh

PREFIX="Loop unprocessed files"
API=http://validator-api/api

# loop forever
while :
do

  # request a file to be processed
  
  DATASET=`curl -s --header 'Accept: application/xml' \
  'http://www.dataworkbench.io/api/iati-datasets?filter=%7B%20%20%20%22limit%22%3A%201%2C%20%20%20%20%22where%22%3A%20%7B%20%20%20%22and%22%3A%20%5B%20%20%20%20%20%20%20%7B%22svrl-updated%22%3A%20%7B%22exists%22%3A%20false%7D%2C%20%20%20%20%20%20%20%22processing%22%3A%20%7B%22exists%22%3A%20false%7D%20%20%20%20%20%20%20%7D%20%20%20%20%20%5D%20%20%20%7D%20%7D'`
  
  MD5=`echo $DATASET | xmllint --xpath '//md5/text()' -`
  DSID=`echo $DATASET | xmllint --xpath '//id/text()' -`
  
  if [ -z $MD5 ]; then
    echo "$PREFIX: Nothing found to process, waiting"
  
  else
    echo "$PREFIX: Found $MD5 -- start processing"
    
    NOW=`date --iso-8601=seconds`
    APIDATA="{\"processing\": \"$NOW\"}"
  
    echo "$PREFIX: update iati-datasets $MD5 to indicate processing"
    curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' \
    -d "$APIDATA" \
    "$API/iati-datasets/upsertWithWhere?where=%7B%22id%22%3A%22$DSID%22%7D"

    echo "$PREFIX: process $MD5"
    ./webhook-scripts/inhouse.sh $MD5    
  fi
  
  echo "$PREFIX: Loop unprocessed files: wait a minute"
  sleep 10m
done