#!/usr/bin/env bash

# Check the input files for well-formedness and schema errors, produce a feedback file if appropriate

WORKSPACE=/workspace
INPUTDIR=${1:-input}
SRCDIR=${2:-src}
FILEMASK=${3}*
PREFIX="XML check"
API=http://validator-api/api

mkdir -p \
  $WORKSPACE/tmp/xmltest \
  $WORKSPACE/tmp/xmltestlog \
  $WORKSPACE/tmp/xmlschemalog \
  $WORKSPACE/tmp/iatifeedback \
  $WORKSPACE/tmp/feedback \
  $WORKSPACE/input \
  $WORKSPACE/dest

cd $WORKSPACE/$INPUTDIR
find . -path "./.git" -name "$FILEMASK" -prune -o -type f -print | while read FILE; do

  NAME=`basename $FILE`
  MD5=${NAME%.xml}
  
  cd $WORKSPACE/$INPUTDIR
  xmllint --recover --output "$WORKSPACE/tmp/xmltest/$NAME" "$NAME" 2> "$WORKSPACE/tmp/xmltestlog/$NAME"
  
  if [ -s "$WORKSPACE/tmp/xmltestlog/$NAME" ]; then
    mv "$WORKSPACE/tmp/xmltest/$NAME" $WORKSPACE/$SRCDIR
  else
    cp --preserve $WORKSPACE/$INPUTDIR/$NAME $WORKSPACE/$SRCDIR
    rm "$WORKSPACE/tmp/xmltest/$NAME"
  fi

  cd $WORKSPACE/$SRCDIR
  XMLROOT=`xmllint --xpath "local-name(/*)" "$NAME" 2> /dev/null`
  XMLATTR=`xmllint --xpath "string(/*/@version)" "$NAME" 2> /dev/null`
  
  if [[ "$XMLROOT." == "iati-activities." || "$XMLROOT." == "iati-organisations." ]]; then
    if [[ $XMLATTR. =~ 1\.0[1-5]\. || $XMLATTR. =~ 2\.0[1-3]\. ]]; then
      VERSION=$XMLATTR
    elif [[ $XMLATTR. =~ 1\..* ]]; then
      VERSION=1.05
    else
      VERSION=2.03
    fi
    
    if xmllint --noout --schema /home/lib/schemata/$VERSION/$XMLROOT-schema.xsd "$NAME" 2> "$WORKSPACE/tmp/xmlschemalog/$NAME"; then
      rm "$WORKSPACE/tmp/xmlschemalog/$NAME"
      if [ -s "$WORKSPACE/tmp/xmltestlog/$NAME" ]; then
        echo '<recovered-iati-file/>' > "$WORKSPACE/tmp/iatifeedback/$NAME"
        echo "$PREFIX $MD5: recovered-iati-file"
        
        APIDATA="{\"md5\": \"$MD5\", \"file-type\": \"recovered-iati-file\", \"iati-version\": \"$VERSION\"}"

        curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' \
          -d "$APIDATA" \
          "$API/iati-datasets/update?where=%7B%22md5%22%3A%22$MD5%22%7D"
        
      else
        echo '<iati-file/>' > "$WORKSPACE/tmp/iatifeedback/$NAME"
        echo "$PREFIX $MD5: iati-file"
        
        APIDATA="{\"md5\": \"$MD5\", \"file-type\": \"iati-file\", \"iati-version\": \"$VERSION\"}"

        curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' \
          -d "$APIDATA" \
          "$API/iati-datasets/update?where=%7B%22md5%22%3A%22$MD5%22%7D"
        
      fi
    else
      if [ -s "$WORKSPACE/tmp/xmltestlog/$NAME" ]; then
        echo '<recovered-iati-file-with-schema-errors/>' > "$WORKSPACE/tmp/iatifeedback/$NAME"
        echo "$PREFIX $MD5: recovered-iati-file-with-schema-errors"

        APIDATA="{\"md5\": \"$MD5\", \"file-type\": \"recovered-iati-file-with-schema-errors\", \"iati-version\": \"$VERSION\"}"

        curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' \
          -d "$APIDATA" \
          "$API/iati-datasets/update?where=%7B%22md5%22%3A%22$MD5%22%7D"
        
      else
        echo '<iati-file-with-schema-errors/>' > "$WORKSPACE/tmp/iatifeedback/$NAME"
        echo "$PREFIX $MD5: iati-file-with-schema-errors"

        APIDATA="{\"md5\": \"$MD5\", \"file-type\": \"iati-file-with-schema-errors\", \"iati-version\": \"$VERSION\"}"

        curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' \
          -d "$APIDATA" \
          "$API/iati-datasets/update?where=%7B%22md5%22%3A%22$MD5%22%7D"

      fi       
    fi
    
  
  elif [ -s "$WORKSPACE/tmp/xmltestlog/$NAME" ]; then
     
    echo '<not-an-xml-file/>' > "$WORKSPACE/tmp/feedback/$NAME"
    echo "$PREFIX $MD5: not-an-xml-file"
    rm "$WORKSPACE/src/$NAME"
    
    APIDATA="{\"md5\": \"$MD5\", \"file-type\": \"not-an-xml-file\"}"

    curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' \
      -d "$APIDATA" \
      "$API/iati-datasets/update?where=%7B%22md5%22%3A%22$MD5%22%7D"
    
  else
    echo '<not-an-iati-file/>' > "$WORKSPACE/tmp/feedback/$NAME"
    echo "$PREFIX $MD5: not-an-iati-file"
    rm "$WORKSPACE/src/$NAME"

    APIDATA="{\"md5\": \"$MD5\", \"file-type\": \"not-an-iati-file\"}"

    curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' \
      -d "$APIDATA" \
      "$API/iati-datasets/update?where=%7B%22md5%22%3A%22$MD5%22%7D"
  fi 

done

