#!/bin/bash
echo -e "\nRunning in developer mode: using the engine source code at $MY_PATH\n"

OTHER_VOLUMES="-v ${MY_PATH}/engine:/home -v ${MY_PATH}/develop:/develop"

if [ "$1." = "root." ]; then
  USER="0:0"
  PARAMETERS=${@:2}
  ENTRY="--entrypoint=/bin/bash -it"
elif [ "$1." = "bash." ]; then
  PARAMETERS=${@:2}
  ENTRY="--entrypoint=/bin/bash -it"
fi
